'use strict';
const canonical = {match:'product',topology:'both',graph_join:'union',facet:'separate_facet_sum',description:'multiply',scope:'equal_depth',recovery:'on'};
const defaultCoefficients = [1,.25,.25,.25,.25];
const facetNames = ['topic','temporal','why','activity','concreteness'];
let comparisonCoefficients = [...defaultCoefficients];
let leaderboardData = null;
const definitions = {
  match:['Tag matching','How query tags support graph tags and chunks.'],
  topology:['Graph routes','Which existing structural paths can carry support.'],
  graph_join:['Graph join','Union, intersection, or graph support alone.'],
  facet:['Facet combination','How the separate facet contributions combine.'],
  description:['Description','How the whole-query description affects the score.'],
  scope:['Area nomination','How structural areas nominate alongside global routes.'],
  recovery:['Source recovery','Whether connected source-record parts move together.']
};
const $ = id => document.getElementById(id);
let comparison = {...canonical}, result = null, status = null, debounce = null, request = 0, controller = null;
const selects = {};
const coefficientInputs = facetNames.map(name=>$('coefficient-'+name));
const coefficientValues = () => coefficientInputs.map(input=>input.valueAsNumber);
const coefficientsActive = () => selects.facet.value==='separate_facet_sum';
const effectiveCoefficients = () => coefficientsActive()?coefficientValues():[...defaultCoefficients];
function setCoefficients(values){coefficientInputs.forEach((input,i)=>{input.value=values[i];});}
function coefficientLabel(values){return facetNames.map((name,i)=>name+'='+values[i]).join(', ');}
function coefficientPolicyLabel(p,values){return policyLabel(p)+(p.facet==='separate_facet_sum'?' ['+coefficientLabel(values)+']':'');}
const text = (tag, value, cls) => {const n=document.createElement(tag); n.textContent=value; if(cls)n.className=cls; return n;};
const number = x => x == null || !Number.isFinite(Number(x)) ? '—' : Number(x).toLocaleString(undefined,{maximumFractionDigits:0});
const rate = x => x == null || !Number.isFinite(Number(x)) ? '—' : (Number(x)*100).toFixed(2)+'%';
const score = x => x == null || !Number.isFinite(Number(x)) ? '—' : Number(x).toFixed(5);
const policy = () => Object.fromEntries(Object.keys(canonical).map(k=>[k,selects[k].value]));
const samePolicy = (a,b) => Object.keys(canonical).every(k=>a[k]===b[k]);
function policyLabel(p){return Object.keys(canonical).map(k=>p[k]).join(' / ');}
function markPolicy(){const changed=!samePolicy(policy(),canonical)||(coefficientsActive()&&coefficientValues().some((v,i)=>v!==defaultCoefficients[i])); $('policy-kind').textContent=changed?'Exploratory variant':'Canonical policy'; $('policy-kind').classList.toggle('exploratory',changed); $('comparison-label').textContent=coefficientPolicyLabel(comparison,comparisonCoefficients);}
function constrain(){if(selects.topology.value==='none'){selects.graph_join.value='union';selects.graph_join.disabled=true;}else selects.graph_join.disabled=false;const active=coefficientsActive();coefficientInputs.forEach(input=>{input.disabled=!active;});$('coefficient-controls').classList.toggle('inactive',!active);$('coefficient-state').textContent=active?'Applied only to separate facet sum. Use finite nonnegative values; coefficients are not normalized.':'Inactive in this facet mode. Stored values apply when you return to separate facet sum.';}
function schedule(){constrain();markPolicy(); if($('live').checked){clearTimeout(debounce);debounce=setTimeout(replay,300);}}
Object.entries(definitions).forEach(([key,[label,note]],i)=>{const wrap=text('label','');const head=text('span','', 'operator-label');head.append(text('span',i+1,'step'),text('span',label));const select=document.createElement('select');select.id='operator-'+key;select.name=key;select.setAttribute('aria-label',label);select.append(new Option(canonical[key].replaceAll('_',' '),canonical[key]));select.value=canonical[key];select.addEventListener('change',schedule);selects[key]=select;wrap.append(head,select,text('span',note,'operator-note'));$('operators').append(wrap);});
function updateCaseMeta(){const c=status?.cases?.find(c=>c.case_id===$('case').value);$('cohort').textContent=c?.cohort||'';updateSelectedBest();}
async function loadStatus(){try{const response=await fetch('/api/status',{cache:'no-store'});if(!response.ok)throw new Error('Status service returned '+response.status);const next=await response.json();status=next;const old=$('case').value;const cases=next.cases||[];$('case').replaceChildren(...cases.map(c=>new Option(c.question_id||c.case_id,c.case_id)));if(cases.some(c=>c.case_id===old))$('case').value=old;
  Object.keys(selects).forEach(k=>{const opts=next.factors?.[k];if(!Array.isArray(opts)||!opts.length)return;const oldValue=selects[k].value;selects[k].replaceChildren(...opts.map(o=>{const value=typeof o==='object'?(o.value??o.id??o.name):o;const label=typeof o==='object'?(o.label??value):String(o).replaceAll('_',' ');return new Option(label,value);}));if([...selects[k].options].some(o=>o.value===oldValue))selects[k].value=oldValue;});
  $('connection').textContent=cases.length?'Cached inputs ready':'Preparing cached inputs';$('case-count').textContent=number(next.ready_cases??cases.length)+' / '+number(next.expected_cases)+' cases ready';$('replay').disabled=!cases.length;updateCaseMeta();constrain();markPolicy();if(!result&&cases.length&&!controller)replay();
}catch(e){$('connection').textContent='Service unavailable';showError('Cannot read the local replay service. '+e.message);}finally{setTimeout(loadStatus, status && status.ready_cases>=status.expected_cases ? 30000 : 5000);}}
function showError(message){$('error').textContent=message;$('error').hidden=!message;}
async function replay(){clearTimeout(debounce);const id=$('case').value;if(!id)return;constrain();if(coefficientsActive()&&coefficientInputs.some(input=>!input.validity.valid||!Number.isFinite(input.valueAsNumber)||input.valueAsNumber<0)){showError('Each facet coefficient must be a finite nonnegative number.');$('busy').textContent='Fix the coefficient values to replay';return;}const requestedCoefficients=effectiveCoefficients();const requestedComparisonCoefficients=[...comparisonCoefficients];const serial=++request;controller?.abort();const active=new AbortController();controller=active;$('busy').textContent='Replaying cached routes…';$('replay').disabled=true;showError('');try{const response=await fetch('/api/replay',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({case_id:id,policy:policy(),compare_policy:comparison,coefficients:requestedCoefficients,compare_coefficients:requestedComparisonCoefficients}),signal:active.signal});const data=await response.json();if(!response.ok)throw new Error(data.error||data.detail||'Replay returned '+response.status);if(serial!==request)return;result={...data,coefficients:data.coefficients??requestedCoefficients,comparison_coefficients:data.comparison_coefficients??data.compare_coefficients??requestedComparisonCoefficients};render();$('pin').disabled=false;$('busy').textContent='Replay complete · no model calls';}catch(e){if(e.name!=='AbortError'&&serial===request){showError(e.message);$('busy').textContent='Replay failed';}}finally{if(serial===request){controller=null;$('replay').disabled=false;}}}
function renderMetrics(){const a=result.summary||{},b=result.comparison_summary||{};const metrics=[['Source-ID recall',rate(a.recall_id),rate(b.recall_id),a.recall_id,b.recall_id,number(a.hits)+' / '+number(a.gold_count)+' reference IDs retrieved'],['Source-ID precision',rate(a.precision_id),rate(b.precision_id),a.precision_id,b.precision_id,number(a.hits)+' / '+number(a.retrieved_ids)+' retrieved IDs in reference'],['Delivered characters',number(a.delivered_chars),number(b.delivered_chars),null,null,'Budget: 72,000 serialized characters'],['Full chunks',number(a.full_chunks),number(b.full_chunks),null,null,a.partial_chunk_id?'Plus one partial boundary chunk':'No partial boundary chunk']];$('metrics').replaceChildren();metrics.forEach(([label,value,old,v,w,detail])=>{const node=text('div','','metric');node.append(text('div',label,'metric-label'),text('div',value,'metric-value'));const sub=text('div','Comparison '+old,'metric-detail');if(v!=null&&w!=null){const delta=(v-w)*100;sub.append(text('span',' · '+(delta>0?'+':'')+delta.toFixed(2)+' pp',delta>0?'gain':delta<0?'loss':'muted'));}node.append(sub,text('div',detail,'metric-detail'));$('metrics').append(node);});}
function pair(oldValue,newValue,rank=true){const n=text('span','','rank-pair');n.append(text('span',number(oldValue),'muted'),text('span','→','arrow'),text('strong',number(newValue)));if(rank&&oldValue!=null&&newValue!=null&&oldValue!==newValue){const delta=oldValue-newValue;n.append(text('span',(delta>0?'↑ ':'↓ ')+number(Math.abs(delta)), 'delta '+(delta>0?'gain':'loss')));}return n;}
function deliveryState(oldValue,newValue){const cls=newValue?(oldValue?'retained':'gain'):(oldValue?'loss':'muted');const label=newValue?(oldValue?'Retained':'Entered budget'):(oldValue?'Left budget':'Outside budget');const n=text('span','','delivery '+cls);n.append(text('span','','dot'),text('span',label));return n;}
function isChanged(m){return m.old_rank!==m.new_rank||m.old_position!==m.new_position||m.old_delivered!==m.new_delivered;}
function renderRows(){if(!result)return;const all=[...(result.movements||[])].sort((a,b)=>(a.new_rank??Infinity)-(b.new_rank??Infinity)||String(a.chunk_id).localeCompare(String(b.chunk_id)));const top=new Set(all.slice(0,100).map(m=>m.chunk_id));const query=$('search').value.trim().toLowerCase();const rows=all.filter(m=>(query||top.has(m.chunk_id)||($('include-gold').checked&&m.gold_pointer_count>0))&&(!query||String(m.chunk_id).toLowerCase().includes(query))&&(!$('gold-only').checked||m.gold_pointer_count>0)&&(!$('changed-only').checked||isChanged(m))&&(!$('delivered-only').checked||m.old_delivered||m.new_delivered));const fragment=document.createDocumentFragment();for(const m of rows){const row=document.createElement('tr');const cell=document.createElement('td');const button=text('button',m.chunk_id,'chunk-button');button.title=m.chunk_id;button.addEventListener('click',()=>inspect(m));cell.append(button);if(m.gold_pointer_count)cell.append(text('span',number(m.gold_pointer_count)+' gold','gold-count'));row.append(cell);const rank=document.createElement('td');rank.append(pair(m.old_rank,m.new_rank));row.append(rank);const pos=document.createElement('td');pos.append(pair(m.old_position,m.new_position));row.append(pos);const delivered=document.createElement('td');delivered.append(deliveryState(m.old_delivered,m.new_delivered));row.append(delivered);row.append(text('td',score(m.old_score)+' → '+score(m.score),'numeric'));fragment.append(row);}$('rows').replaceChildren(fragment);$('row-count').textContent=number(rows.length)+' shown / '+number(all.length)+' ranked chunks';$('empty').hidden=rows.length>0;$('empty').textContent='No chunks match these filters.';}
function renderPointers(){if(!result)return;const all=result.gold_pointers||[];const rows=all.filter(p=>!$('pointer-changes').checked||p.old_credited!==p.new_credited);const frag=document.createDocumentFragment();rows.forEach(p=>{const card=text('div','','pointer');card.append(text('code',p.artifact_id));const meta=text('div','','pointer-meta');meta.append(text('span',number(p.chunk_ids?.length??0)+' linked chunks'),deliveryState(p.old_credited,p.new_credited));card.append(meta);card.title=(p.chunk_ids||[]).join('\n');frag.append(card);});$('pointers').replaceChildren(frag);$('pointer-count').textContent=number(rows.length)+' / '+number(all.length)+' reference source IDs · '+number(all.filter(p=>!p.old_credited&&p.new_credited).length)+' gained · '+number(all.filter(p=>p.old_credited&&!p.new_credited).length)+' lost';}
function inspect(m){$('inspect').hidden=false;$('inspect-id').textContent=m.chunk_id;const allowed=new Set(['edge_id','graph_tag','graph_tag_id','graph_tag_index','seed_chunk_id','route_type','query_tag_index','facet','coefficient','contribution','Z','Q','u','F','M','D_seed','D_target','hop_discount']);function safe(value){if(Array.isArray(value))return value.map(safe);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([k,v])=>allowed.has(k)||(v&&typeof v==='object')).map(([k,v])=>[k,safe(v)]));return value;}$('inspect-paths').textContent=m.paths?JSON.stringify(safe(m.paths),null,2):'No route pointers supplied for this replay. Score and delivery movements are shown above.';$('inspect').scrollIntoView({behavior:'smooth',block:'start'});}
function render(){renderMetrics();renderRows();renderPointers();renderGoldPlot();const item=status?.cases?.find(c=>c.case_id===result.case_id);$('displayed-case').textContent='Displayed: '+(item?.question_id||result.case_id)+' · '+coefficientPolicyLabel(result.policy||policy(),result.coefficients??defaultCoefficients)+' · compared with '+coefficientPolicyLabel(result.comparison_policy||comparison,result.comparison_coefficients??comparisonCoefficients);$('timing').textContent=number(result.timing_ms)+' ms · cached replay';$('inspect').hidden=true;}
let leaderboardRequest=0, leaderboardTimer=null, leaderboardAbort=null;
function metricCell(value,baseline){const cell=text('td','','numeric');cell.append(text('strong',rate(value)));if(value!=null&&baseline!=null){const d=(value-baseline)*100;cell.append(text('div',(d>0?'+':'')+d.toFixed(2)+' pp vs canonical','metric-detail '+(d>0?'gain':d<0?'loss':'muted')));}return cell;}
function loadLeaderPolicy(next,coefficients=defaultCoefficients){
  const missing=Object.keys(canonical).filter(k=>!Object.prototype.hasOwnProperty.call(next,k)||![...selects[k].options].some(o=>o.value===String(next[k])));
  if(missing.length){showError('This setting cannot be loaded into the current replay controls: '+missing.join(', ')+'. Refresh the available cases and try again.');return;}
  if(!Array.isArray(coefficients)||coefficients.length!==5||coefficients.some(v=>typeof v!=='number'||!Number.isFinite(v)||v<0)){showError('The ranked setting has invalid facet coefficients.');return;}
  Object.keys(canonical).forEach(k=>{selects[k].value=String(next[k]);});setCoefficients(coefficients);constrain();markPolicy();replay();$('operators').scrollIntoView({behavior:'smooth',block:'center'});
}
function selectedBest(){return leaderboardData?.best_per_query?.cases?.find(c=>String(c.case_id)===String($('case').value));}
function updateSelectedBest(){
  const selected=selectedBest();$('load-selected-best').disabled=!selected?.policy;
  if(!selected){$('selected-best-description').textContent='No completed setting for this case in the displayed leaderboard subset.';return;}
  const names={recall_id:'source-ID recall',precision_id:'source-ID precision',f1_id:'source-ID F1'};
  const chosen=names[leaderboardData.ranking_metric]||'the ranking metric';
  $('selected-best-description').textContent=(selected.question_id||selected.case_id)+' · chosen by '+chosen+' · recall '+rate(selected.recall_id)+' · precision '+rate(selected.precision_id)+' · F1 '+rate(selected.f1_id)+' · '+coefficientPolicyLabel(selected.policy,selected.coefficients??defaultCoefficients);
}

function renderLeaderboard(data){leaderboardData=data;const n=data.completed_cases??0,total=data.expected_cases??0;const metricNames={recall_id:'source-ID recall',precision_id:'source-ID precision',f1_id:'source-ID F1'};const metric=metricNames[data.ranking_metric||$('leader-metric').value];const done=data.status==='complete';$('leader-progress').textContent=(done?'Complete':'Partial results')+' · '+number(n)+' / '+number(total)+' cases';$('leader-progress').className=done?'gain':'pending';$('leader-detail').textContent=number(data.configurations_per_case)+' configurations per case · ranked by '+metric;$('leader-selection-note').textContent=data.selection_space_note||'Tested structures and coefficient settings are ranked separately, including equal scores. Exact duplicate policy-and-coefficient settings are removed.';const base=data.canonical||{};$('leader-baseline').textContent='Canonical on these '+number(n)+' cases: recall '+rate(base.recall_id)+' · precision '+rate(base.precision_id)+' · F1 '+rate(base.f1_id);const leaders=n>0?(data.leaders||[]).slice(0,25):[];const fragment=document.createDocumentFragment();leaders.forEach((entry,i)=>{const row=document.createElement('tr');row.append(text('td',i+1,'leader-rank'));const name=text('td','','leader-policy');name.append(text('strong',entry.label||entry.condition||'Configuration '+(i+1)),text('code',policyLabel(entry.policy||{})));name.append(text('code',coefficientLabel(entry.coefficients??defaultCoefficients)+(entry.policy?.facet==='separate_facet_sum'?'':' (inactive in this facet mode)'),'leader-weights'));if(entry.source)name.append(text('div',entry.source,'metric-detail'));row.append(name,metricCell(entry.recall_id,base.recall_id),metricCell(entry.precision_id,base.precision_id),metricCell(entry.f1_id,base.f1_id));const counts=text('td','','leader-counts');counts.append(text('span',number(entry.recall_better),'gain'),text('span',' / ','muted'),text('span',number(entry.recall_worse),'loss'),text('span',' / '+number(entry.recall_tied),'muted'));row.append(counts);const action=document.createElement('td');const button=text('button','Load setting');button.disabled=!entry.policy;button.addEventListener('click',()=>loadLeaderPolicy(entry.policy,entry.coefficients??defaultCoefficients));action.append(button);row.append(action);fragment.append(row);});$('leader-rows').replaceChildren(fragment);$('leader-empty').hidden=leaders.length>0;const best=data.best_per_query||{};$('oracle-label').textContent=best.label||'Uses reference outcomes to choose a different policy for each question; this is not a deployable selector.';$('oracle-values').replaceChildren(text('span','Recall '+rate(best.recall_id)),text('span','Precision '+rate(best.precision_id)),text('span','F1 '+rate(best.f1_id)));$('oracle').hidden=!$('show-oracle').checked;updateSelectedBest();}
async function loadLeaderboard(){clearTimeout(leaderboardTimer);const serial=++leaderboardRequest;leaderboardAbort?.abort();const abort=new AbortController();leaderboardAbort=abort;try{const response=await fetch('/api/leaderboard?metric='+encodeURIComponent($('leader-metric').value)+'&subset='+encodeURIComponent($('leader-subset').value)+'&limit=25',{cache:'no-store',signal:abort.signal});const data=await response.json();if(!response.ok)throw new Error(data.error||'Leaderboard returned '+response.status);if(serial!==leaderboardRequest)return;renderLeaderboard(data);$('leader-error').hidden=true;}catch(e){if(e.name!=='AbortError'&&serial===leaderboardRequest){$('leader-error').textContent='Leaderboard update failed. Previous results, if shown, have not been refreshed. '+e.message;$('leader-error').hidden=false;}}finally{if(serial===leaderboardRequest){leaderboardAbort=null;leaderboardTimer=setTimeout(loadLeaderboard,15000);}}}
$('leader-metric').addEventListener('change',loadLeaderboard);$('leader-subset').addEventListener('change',loadLeaderboard);$('load-selected-best').addEventListener('click',()=>{const selected=selectedBest();if(selected)loadLeaderPolicy(selected.policy,selected.coefficients??defaultCoefficients);});$('show-oracle').addEventListener('change',()=>{$('oracle').hidden=!$('show-oracle').checked;});loadLeaderboard();
$('case').addEventListener('change',()=>{updateCaseMeta();schedule();});$('replay').addEventListener('click',replay);$('live').addEventListener('change',()=>{if($('live').checked)schedule();});$('pin').addEventListener('click',()=>{if(!result)return;comparison={...(result.policy||policy())};comparisonCoefficients=[...(result.coefficients??defaultCoefficients)];markPolicy();replay();});$('reset').addEventListener('click',()=>{Object.keys(canonical).forEach(k=>selects[k].value=canonical[k]);comparison={...canonical};comparisonCoefficients=[...defaultCoefficients];setCoefficients(defaultCoefficients);constrain();markPolicy();replay();});$('area-preset').addEventListener('click',()=>{const option=[...selects.scope.options].find(o=>o.value==='area_first');if(!option){showError('The area-first variant is not available from this service yet.');return;}selects.scope.value='area_first';markPolicy();replay();});['search','include-gold','gold-only','changed-only','delivered-only'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',renderRows));$('pointer-changes').addEventListener('change',renderPointers);$('close-inspect').addEventListener('click',()=>{$('inspect').hidden=true;});coefficientInputs.forEach(input=>input.addEventListener('input',schedule));constrain();markPolicy();loadStatus();
function renderGoldPlot(){
  const movements=(result?.movements||[]).filter(m=>m.gold_pointer_count>0);
  $('gold-position-plot').hidden=!movements.length;
  $('gold-plot').replaceChildren();
  if(!movements.length)return;
  const ns='http://www.w3.org/2000/svg';
  const element=(tag,attrs={},value)=>{const node=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>node.setAttribute(k,String(v)));if(value!=null)node.textContent=value;return node;};
  const svg=element('svg',{viewBox:'0 0 1120 294',role:'group','aria-labelledby':'gold-plot-caption'});
  const left=178,right=942,top=35,bottom=240,terminal=274;
  const maximum=Math.max(4808,...movements.flatMap(m=>[m.old_position||0,m.new_position||0]));
  const supported=p=>Number.isFinite(Number(p))&&Number(p)>=1;
  const y=p=>supported(p)?top+Math.log(Math.min(Number(p),maximum))/Math.log(maximum)*(bottom-top):terminal;
  svg.append(element('text',{x:left,y:17,'text-anchor':'middle',class:'plot-label'},'Comparison delivery position'),element('text',{x:right,y:17,'text-anchor':'middle',class:'plot-label'},'Current delivery position'));
  [1,10,100,1000,maximum].forEach(tick=>{const at=y(tick);svg.append(element('line',{x1:left,y1:at,x2:right,y2:at,class:'plot-grid'}));svg.append(element('text',{x:left-14,y:at+4,'text-anchor':'end',class:'plot-tick'},number(tick)),element('text',{x:right+14,y:at+4,'text-anchor':'start',class:'plot-tick'},number(tick)));});
  [left,right].forEach(x=>svg.append(element('line',{x1:x,y1:top,x2:x,y2:bottom,class:'plot-axis'})));
  svg.append(element('text',{x:left-14,y:terminal+4,'text-anchor':'end',class:'plot-tick'},'Unsupported'),element('text',{x:right+14,y:terminal+4,'text-anchor':'start',class:'plot-tick'},'Unsupported'));
  const lines=element('g');
  movements.forEach(m=>{const old=supported(m.old_position)?Number(m.old_position):Infinity;const current=supported(m.new_position)?Number(m.new_position):Infinity;const direction=current<old?'gain':current>old?'loss':'steady';const group=element('g',{class:'plot-route '+direction});const description=m.chunk_id+' · '+(supported(m.old_position)?m.old_position:'unsupported')+' → '+(supported(m.new_position)?m.new_position:'unsupported')+' · '+m.gold_pointer_count+' gold pointers';group.append(element('title',{},description),element('line',{x1:left,y1:y(m.old_position),x2:right,y2:y(m.new_position),class:'plot-link'}));const radius=Math.min(5,2+Math.sqrt(m.gold_pointer_count)*.55);[[left,m.old_position],[right,m.new_position]].forEach(([x,pos])=>{const point=element('circle',{cx:x,cy:y(pos),r:radius,class:'plot-point'+(!supported(pos)?' unsupported':''),tabindex:0,role:'button','aria-label':description});const select=()=>{$('search').value=m.chunk_id;$('changed-only').checked=false;$('delivered-only').checked=false;renderRows();$('search').focus();};point.addEventListener('click',select);point.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();select();}});group.append(point);});lines.append(group);});
  svg.append(lines);
  [[left,result.comparison_summary?.full_chunks,'start'],[right,result.summary?.full_chunks,'end']].forEach(([x,count,anchor])=>{if(count==null)return;const at=count>0?y(Number(count)+.5):top-5;const start=anchor==='start'?x-5:x-200,end=anchor==='start'?x+200:x+5;svg.append(element('line',{x1:start,y1:at,x2:end,y2:at,class:'plot-boundary'}),element('text',{x:anchor==='start'?start+9:end-9,y:at-5,'text-anchor':anchor,class:'plot-boundary-label'},'72k · '+number(count)+' full chunks'));});
  $('gold-plot').append(svg);
}
