"""contract.py — the shared shapes every arm and evaluator imports."""
from dataclasses import dataclass, field


@dataclass
class QuestionWithTruth:
    id: str
    question: str
    type: str  # HERB answer-category (person/content/company/pr/url); "" = unanswerable. a/u also in the id.
    ground_truth: list[str]
    citations: list[str]


@dataclass
class ModelUsage:
    """One model's cost — calls / tokens / wall-time. Reused wherever a model is
    touched: the shared generator, an arm's own retrieval model, a build."""
    calls: int = 0
    tokens: int = 0
    time_s: float = 0.0


@dataclass
class ArmOutput:
    answer: str
    contexts: list[str]
    context_ids: list[str]
    search_time_s: float                  # total retrieval wall-time
    generator: ModelUsage = field(default_factory=ModelUsage)  # the shared answer-writer (same role every arm)
    retrieval: ModelUsage = field(default_factory=ModelUsage)  # the arm's OWN model use in retrieval (0 for lucene)


@dataclass
class BuildStats:
    build_time_s: float
    model: ModelUsage                     # the build's model work (e.g. embedding the corpus)
    models: list[str]                     # which model ids the build used


@dataclass
class EvalResult:
    question_id: str
    type: str
    arm: str
    metric: str
    value: float
    status: str
    components: dict
    human_label: str | None


@dataclass
class RunManifest:
    """Provenance for a `questions` run — answers generated by ONE arm."""
    arm: str
    generator_model: str | None  # None on a retrieval-only run (no generation)
    top_k: int
    questions_file: str
    n_questions: int                      # chosen for this run
    n_ran: int                            # produced an answer -> arm_outputs.jsonl
    n_failed: int                         # chosen minus answered (n_ran + n_failed == n_questions)
    timestamp: str
    build_stats: BuildStats


@dataclass
class EvalManifest:
    """Provenance for an `evals` run — ONE scorer over one run file."""
    scorer: str
    judge_model: str | None
    source_run: str
    arm: str
    timestamp: str
